IDReporting/Models/Baglantilar.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Baglantilar
    {
        public int ID { get; set; }
        public Nullable<int> SubeID { get; set; }
        public string Isim { get; set; }
        public string Sunucu { get; set; }
        public string Veritabani { get; set; }
        public string KullaniciAdi { get; set; }
        public string Parola { get; set; }
        public Nullable<int> Port { get; set; }
        public string Sema { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public string KayitYapanKullanici { get; set; }
        public Nullable<System.DateTime> DuzenlemeTarihi { get; set; }
        public string DuzenlemeYapanKullanici { get; set; }
        public Nullable<bool> Silindi { get; set; }
        public Nullable<System.DateTime> SilinenTarih { get; set; }
        public string SilenKullanici { get; set; }
    }
}

IDReporting/Models/Parametreler.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametreler
    {
        public int ID { get; set; }
        public string Tip { get; set; }
        public string Deger { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public string KayitYapanKullanici { get; set; }
        public Nullable<System.DateTime> DuzenlemeTarihi { get; set; }
        public string DuzenlemeYapanKullanici { get; set; }
        public Nullable<bool> Silindi { get; set; }
        public Nullable<System.DateTime> SilinenTarih { get; set; }
        public string SilenKullanici { get; set; }
    }
}

IDReporting/Controllers/IDController.cs
using IDReporting.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IDReporting.Controllers
{
	public class IDController : Controller
	{

		IDReportingEntities db = new IDReportingEntities();


		#region Genel Parametreler

		[HttpGet]
		public ActionResult GenelParametreler()
		{
			if (!AutoGirisKontrol())
				return Redirect("~/ID/Giris");
			return View(db.Parametrelers.Where((e) => e.Tip.Contains("Parametre_") && e.Silindi == false).ToList());
		}

		[HttpPost]
		public ActionResult GenelParametreler(string Parametre_MailEmail, string Parametre_MailKullaniciAdi, string Parametre_MailParola,
			string Parametre_MailServer, string Parametre_MailPort, string Parametre_MailSSL, string Parametre_Lisans)
		{
			if (!AutoGirisKontrol())
				return Redirect("~/ID/Giris");
			{
				string tip = "Parametre_MailEmail";
				if (db.Parametrelers.Where((e) => e.Tip == tip).Count() > 0)
					db.Parametrelers.Remove(db.Parametrelers.Where((e) => e.Tip == tip).First());
				db.Parametrelers.Add(new Parametreler() { Tip = tip, Deger = Parametre_MailEmail, Silindi = false });
			}
			{
				string tip = "Parametre_MailKullaniciAdi";
				if (db.Parametrelers.Where((e) => e.Tip == tip).Count() > 0)
					db.Parametrelers.Remove(db.Parametrelers.Where((e) => e.Tip == tip).First());
				db.Parametrelers.Add(new Parametreler() { Tip = tip, Deger = Parametre_MailKullaniciAdi, Silindi = false });
			}
			{
				string tip = "Parametre_MailParola";
				if (db.Parametrelers.Where((e) => e.Tip == tip).Count() > 0)
					db.Parametrelers.Remove(db.Parametrelers.Where((e) => e.Tip == tip).First());
				db.Parametrelers.Add(new Parametreler() { Tip = tip, Deger = Parametre_MailParola, Silindi = false });
			}
			{
				string tip = "Parametre_MailServer";
				if (db.Parametrelers.Where((e) => e.Tip == tip).Count() > 0)
					db.Parametrelers.Remove(db.Parametrelers.Where((e) => e.Tip == tip).First());
				db.Parametrelers.Add(new Parametreler() { Tip = tip, Deger = Parametre_MailServer, Silindi = false });
			}
			{
				string tip = "Parametre_MailPort";
				if (db.Parametrelers.Where((e) => e.Tip == tip).Count() > 0)
					db.Parametrelers.Remove(db.Parametrelers.Where((e) => e.Tip == tip).First());
				db.Parametrelers.Add(new Parametreler() { Tip = tip, Deger = Parametre_MailPort, Silindi = false });
			}
			{
				string tip = "Parametre_MailSSL";
				if (db.Parametrelers.Where((e) => e.Tip == tip).Count() > 0)
					db.Parametrelers.Remove(db.Parametrelers.Where((e) => e.Tip == tip).First());
				db.Parametrelers.Add(new Parametreler() { Tip = tip, Deger = Parametre_MailSSL == "E" ? "E" : "H", Silindi = false });
			}

			db.SaveChanges();
			ViewBag.Mesaj = "Parametreler kaydedilmiştir.";
			return View(db.Parametrelers.Where((e) => e.Tip.Contains("Parametre_") && e.Silindi == false).ToList());
		}

		#endregion

		#region Sorgu İşlemleri

		public ActionResult Kategoriler(int KategoriID)
		{
			if (!AutoGirisKontrol())
				return Redirect("~/ID/Giris");
			return View(db.Sorgulars.Where((e)=>e.KategoriID == KategoriID && e.Silindi == false && e.Aktif == true).ToList());
		}

		public JsonResult SorguTipiSec(string SorguTipi, int BaglantiID)
		{
			db.Configuration.ProxyCreationEnabled = false;
			Baglantilar entityBaglanti = db.Baglantilars.Where((e) => e.ID == BaglantiID).FirstOrDefault();
			SqlCommand cmd = new SqlCommand();
			switch (SorguTipi)
			{
				case "Table":
					cmd.CommandText = @"select * from ["+entityBaglanti.Veritabani+"].sys.tables";
					break;
				case "View":
					cmd.CommandText = @"select * from [" + entityBaglanti.Veritabani + "].sys.views";
					break;
				case "Procedure":
					cmd.CommandText = @"select * from [" + entityBaglanti.Veritabani + "].sys.procedures";
					break;
				default:
					break;
			}
			DataTable dt = (DataTable)IDVeritabani.Sorgula(cmd, SorgulaTuru.Tablo,BaglantiID);
			List<IDGrupKodu> results = new List<IDGrupKodu>();
			foreach (DataRow item in dt.Rows)
			{
				results.Add(new IDGrupKodu() { Isim = Convert.ToString(item["name"]) });
			}
			return Json(results, JsonRequestBehavior.AllowGet);
		}

		public ActionResult Sorgular(string Tip = "")
		{
			if (!AutoGirisKontrol())
				return Redirect("~/ID/Giris");
			return View(db.Sorgulars.Where((e) => e.Silindi == false).OrderBy((o) => o.KategoriID).OrderBy((o)=> o.Isim).ToList());
		}

		[HttpGet]
		public ActionResult Sorgu(int id = 0)
		{
			if (!AutoGirisKontrol())
				return Redirect("~/ID/Giris");

			ViewBag.Baglantilar = db.Baglantilars.Where((e) => e.Silindi == false).ToList();
			ViewBag.Kategoriler = db.Parametrelers.Where((e) => e.Silindi == false && e.Tip == "Kategori").ToList();

			return View(db.Sorgulars.Where((e) => e.ID == id).FirstOrDefault());
		}
		[HttpPost]
		public ActionResult Sorgu(int id, string BaglantiID, string Aktif,string Isim,string KategoriID, string SorguMetni, string SorguTipi, string Sube)
		{
			if (!AutoGirisKontrol())
				return Redirect("~/ID/Giris");
			if (id == 0)
			{
				Sorgular entity = new Sorgular();
				entity.SubeID = Convert.ToInt32(Sube);
				entity.KategoriID = Convert.ToInt32(KategoriID);
				entity.SorguTipi = SorguTipi;
				entity.Isim = Isim;
				entity.BaglantiID = Convert.ToInt32(BaglantiID);
				entity.Sorgu = SorguMetni;
				entity.Aktif = Aktif == "1" ? true : false;

				entity.KayitTarihi = DateTime.Now;
				entity.KayitYapanKullanici = GetCookie("KullaniciAdi");
				entity.Silindi = false;
				db.Sorgulars.Add(entity);
			}
			else
			{
				Sorgular entity = db.Sorgulars.Where((e) => e.ID == id).FirstOrDefault();
				entity.BaglantiID = Convert.ToInt32(BaglantiID);
				entity.Aktif = Aktif == "1" ? true : false;
				entity.Isim = Isim;
				entity.KategoriID = Convert.ToInt32(KategoriID);
				entity.Sorgu = SorguMetni;
				entity.SorguTipi = SorguTipi;
				entity.SubeID = Convert.ToInt32(Sube);

				entity.DuzenlemeTarihi = DateTime.Now;
				entity.DuzenlemeYapanKullanici = GetCookie("KullaniciAdi");
				entity.Silindi = false;
			}
			var degerler = db.GetValidationErrors();
			db.SaveChanges();
			return Redirect("~/ID/Sorgular");
		}

		public ActionResult SorguSil(int id)
		{
			if (!AutoGirisKontrol())
				return Redirect("~/ID/Giris");
			Sorgular entity = db.Sorgulars.Where((e) => e.ID == id).First();
			entity.Silindi = true;
			entity.SilinenTarih = DateTime.Now;
			entity.SilenKullanici = GetCookie("KullaniciAdi");
			db.SaveChanges();
			return Redirect("~/ID/Sorgular");

		}

		#endregion

		#region Parametre İşlemleri

		public ActionResult Parametreler(string Tip="")
		{
			if (!AutoGirisKontrol())
				return Redirect("~/ID/Giris");
			return View(db.Parametrelers.Where((e) => e.Silindi == false && e.Tip == Tip).OrderBy((o) => o.Deger).ToList());
		}

		[HttpGet]
		public ActionResult Parametre(int id = 0, string Tip = "")
		{
			if (!AutoGirisKontrol())
				return Redirect("~/ID/Giris");

			return View(db.Parametrelers.Where((e) => e.ID == id).FirstOrDefault());
		}
		[HttpPost]
		public ActionResult Parametre(int id, string Tip = "", string Deger="")
		{
			if (!AutoGirisKontrol())
				return Redirect("~/ID/Giris");
			if (id == 0)
			{
				Parametreler entity = new Parametreler();
				entity.Tip = Tip;
				entity.Deger = Deger;
				entity.KayitTarihi = DateTime.Now;
				entity.KayitYapanKullanici = GetCookie("KullaniciAdi");
				entity.Silindi = false;
				db.Parametrelers.Add(entity);
			}
			else
			{
				Parametreler entity = db.Parametrelers.Where((e) => e.ID == id).FirstOrDefault();
				entity.Deger = Deger;
				entity.DuzenlemeTarihi = DateTime.Now;
				entity.DuzenlemeYapanKullanici = GetCookie("KullaniciAdi");
				entity.Silindi = false;
			}
			db.SaveChanges();
			return Redirect("~/ID/Parametreler/?Tip=" + Tip);
		}

		public ActionResult ParametreSil(int id, string Tip = "")
		{
			if (!AutoGirisKontrol())
				return Redirect("~/ID/Giris");
			Parametreler entity = db.Parametrelers.Where((e) => e.ID == id).First();
			entity.Silindi = true;
			entity.SilinenTarih = DateTime.Now;
			entity.SilenKullanici = GetCookie("KullaniciAdi");
			db.SaveChanges();
			return Redirect("~/ID/Parametreler/?Tip="+Tip);

		}

		#endregion

		#region Bağlantı İşlemleri

		public ActionResult Baglantilar()
		{
			if (!AutoGirisKontrol())
				return Redirect("~/ID/Giris");

			return View(db.Baglantilars.Where((e) => e.Silindi == false).OrderBy((o) => o.Isim).ToList());
		}

		[HttpGet]
		public ActionResult Baglanti(int id = 0)
		{
			if (!AutoGirisKontrol())
				return Redirect("~/ID/Giris");

			return View(db.Baglantilars.Where((e) => e.ID == id).FirstOrDefault());
		}
		[HttpPost]
		public ActionResult Baglanti(int id, string Sunucu, string Veritabani, string KullaniciAdi, string Parola, string Isim, int Port, string Sema, string Sube = "0")
		{
			if (!AutoGirisKontrol())
				return Redirect("~/ID/Giris");
			if (id == 0)
			{
				Baglantilar entity = new Baglantilar();
				entity.SubeID = Convert.ToInt32(Sube);
				entity.Sunucu = Sunucu;
				entity.Veritabani = Veritabani;
				entity.KullaniciAdi = KullaniciAdi;
				entity.Parola = Parola;
				entity.Isim = Isim;
				entity.Port = Port;
				entity.Sema = Sema;
				entity.KayitTarihi = DateTime.Now;
				entity.KayitYapanKullanici = GetCookie("KullaniciAdi");
				entity.Silindi = false;
				db.Baglantilars.Add(entity);
			}
			else
			{
				Baglantilar entity = db.Baglantilars.Where((e) => e.ID == id).FirstOrDefault();
				entity.SubeID = Convert.ToInt32(Sube);
				entity.Sunucu = Sunucu;
				entity.Veritabani = Veritabani;
				entity.KullaniciAdi = KullaniciAdi;
				entity.Parola = Parola;
				entity.Isim = Isim;
				entity.Port = Port;
				entity.Sema = Sema;
				entity.DuzenlemeTarihi = DateTime.Now;
				entity.DuzenlemeYapanKullanici = GetCookie("KullaniciAdi");
				entity.Silindi = false;
			}
			db.SaveChanges();
			return Redirect("~/ID/Baglantilar");
		}

IDReporting/Controllers/RaporController.cs
using IDReporting.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IDReporting.Controllers
{
	public class RaporController : Controller
	{
		IDReportingEntities db = new IDReportingEntities();
		// GET: Sorgu
		public ActionResult Sorgu(int id = 0)
		{
			if (!AutoGirisKontrol())
				return Redirect("~/ID/Giris");
			if (id == 0)
			{
				return Redirect("~/ID/Giris");
			}
			Sorgular entity = db.Sorgulars.Where((e) => e.ID == id).First();
			return View(entity);
		}

		public ActionResult Goster(int id, FormCollection formCollection)
		{
			if (!AutoGirisKontrol())
				return Redirect("~/ID/Giris");

			Sorgular entitySorgu = db.Sorgulars.Where((e) => e.ID == id).First();
			ViewBag.SorguID = entitySorgu.ID;

			Baglantilar entityBaglanti = db.Baglantilars.Where((e) => e.ID == entitySorgu.BaglantiID).FirstOrDefault();

			db.Filtrelers.RemoveRange(db.Filtrelers.Where((e)=>e.SorguID == entitySorgu.ID));

			DataSet ds = new DataSet();

			string kisit = " Where 1=1";
			string kisitProcedure = " ";
			#region Kisit Ayarlanması
			foreach (var item in formCollection.AllKeys)
			{
				if (item.StartsWith("Secim_"))
				{
					string _id = item.Split('_')[2];
					string kolonadi = formCollection.AllKeys.Where((e) => e.EndsWith("_" + _id)).ToList()[1].Split('_')[1];
					string kolontipi = formCollection.AllKeys.Where((e) => e.EndsWith("_" + _id)).ToList()[1].Split('_')[2];
					string FiltreTipi = formCollection.AllKeys.Where((e) => e.EndsWith("_" + _id)).ToList()[2];
					string deger = "";
					try
					{
						deger = formCollection.AllKeys.Where((e) => e.EndsWith("_" + _id)).ToList()[3];
					}
					catch
					{
						deger = "Deger_"+ kolonadi + "_"+_id;
					}
					string isaret = formCollection.Get(FiltreTipi);
					string kisitDeger = formCollection.Get(deger);
					if (kolontipi == "Boolean" && kisitDeger == null)
					{
						kisitDeger = "0";
					}
					else if (kolontipi == "Boolean" && kisitDeger != null)
					{
						kisitDeger = "1";
					}
					kisit += " and " + kolonadi + " " + isaret + " '" + kisitDeger + "'";
					kisitProcedure += " '" + kisitDeger + "' ";
					Filtreler entityFiltre = new Filtreler();
					entityFiltre.Silindi = false;
					entityFiltre.KayitTarihi = DateTime.Now;
					entityFiltre.KayitYapanKullanici = GetCookie("KullaniciAdi");
					entityFiltre.SorguID = entitySorgu.ID;
					entityFiltre.FiltreTipi = isaret;
					entityFiltre.ParemetreAdi = kolonadi;
					entityFiltre.ParametreDegeri = kisitDeger;
					db.Filtrelers.Add(entityFiltre);
				}
			}
			db.SaveChanges();

			#endregion


		SqlCommand cmd = new SqlCommand();
			switch (entitySorgu.SorguTipi)
			{
				case "Table":
					cmd.CommandText = @"select * from [" + entityBaglanti.Veritabani + "]." + entityBaglanti.Sema + "." + entitySorgu.Sorgu+" "+kisit;
					break;
				case "View":
					cmd.CommandText = @"select * from [" + entityBaglanti.Veritabani + "]." + entityBaglanti.Sema + "." + entitySorgu.Sorgu + " " + kisit;
					break;
				case "Procedure":
					cmd.CommandText = @"Exec [" + entityBaglanti.Veritabani + "]."+ entityBaglanti.Sema + "."+entitySorgu.Sorgu + " " + kisitProcedure;
					break;
				default:
					break;
			}

			ds = (DataSet)IDVeritabani.Sorgula(cmd, SorgulaTuru.DataSet,entityBaglanti.ID);
			
			return View(ds);
		}
		
		public ActionResult GorunumKaydet(int SorguID, string Basliklar)
		{
			string _kullanici = GetCookie("KullaniciAdi");
			if (db.Gorunumlers.Where((e) => e.Kullanici == _kullanici && e.SorguID == SorguID).Count() > 0)
			{
				db.Gorunumlers.RemoveRange(db.Gorunumlers.Where((e) => e.Kullanici == _kullanici && e.SorguID == SorguID));
			}
			db.Gorunumlers.Add(new Gorunumler() {
					Kullanici = GetCookie("KullaniciAdi"),
					SorguID = SorguID,
					EkAciklama1 = Basliklar
			});
			db.SaveChanges();
			return Json("", JsonRequestBehavior.AllowGet);
		}


		#region Kullanıcı Giriş İşlemleri

		public bool AutoGirisKontrol()
		{
			bool GirisKontrol = false;

			string KullaniciAdi = GetCookie("KullaniciAdi");
			string Parola = GetCookie("Parola");

			if (KullaniciAdi != null)
			{
				if (db.Kullanicilars.Where((e) => e.KullaniciAdi == KullaniciAdi && e.Parola == Parola && e.Silindi == false && e.Aktif == true).Count() > 0)
				{
					GirisKontrol = true;
				}
				else
				{
					GirisKontrol = false;
				}
			}

			return GirisKontrol;
		}

		#endregion

		#region Cookie İşlemleri

		private void CreateCookie(string name, string value)
		{
			HttpCookie cookieVisitor = new HttpCookie(name, Server.UrlEncode(value));
			// cookieVisitor.Expires = DateTime.Now.AddDays(2);
			Response.Cookies.Add(cookieVisitor);
		}
		private string GetCookie(string name)
		{
			//Böyle bir cookie mevcut mu kontrol ediyoruz
			if (Request.Cookies.AllKeys.Contains(name))
			{
				//böyle bir cookie varsa bize geri değeri döndürsün
				return Server.UrlDecode(Request.Cookies[name].Value);
			}
			return null;
		}
		private void DeleteCookie(string name)
		{
			//Böyle bir cookie var mı kontrol ediyoruz
			if (GetCookie(name) != null)
			{
				//Varsa cookiemizi temizliyoruz
				Response.Cookies.Remove(name);
				//ya da 
				Response.Cookies[name].Expires = DateTime.Now.AddDays(-1);
			}
		}

		#endregion
	}
}

IDReporting/Views/ID/Baglanti.cshtml
@model IDReporting.Models.Baglantilar
@{
    ViewBag.Title = "Bağlantı";
    IDReporting.Models.Baglantilar entity = new IDReporting.Models.Baglantilar();
    if (Model != null)
    {
        entity = Model;
    }
    else
    {
        entity.ID = 0;
        entity.SubeID = 0;

    }
}
<h4>Kullanıcı Bilgisi #@entity.ID</h4>
<form action="@Url.Action("Baglanti","ID",null)" method="post">
    <input type="hidden" name="id" value="@entity.ID" />
    <input type="hidden" name="Sube" value="@entity.SubeID" />
    <div class="row">
        <div class="col-12 col-sm-12">
            <label>İsim</label>
            <input type="text" name="Isim" value="@entity.Isim" class="form-control" />
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-sm-2">
            <label>Sunucu</label>
            <input type="text" name="Sunucu" value="@entity.Sunucu" class="form-control" />
        </div>
        <div class="col-12 col-sm-2">
            <label>Veritabanı</label>
            <input type="text" name="Veritabani" value="@entity.Veritabani" class="form-control" />
        </div>
        <div class="col-12 col-sm-2">
            <label>Kullanıcı Adı</label>
            <input type="text" name="KullaniciAdi" value="@entity.KullaniciAdi" class="form-control" />
        </div>
        <div class="col-12 col-sm-2">
            <label>Parola</label>
            <input type="password" name="Parola" value="@entity.Parola" class="form-control" />
        </div>
        <div class="col-12 col-sm-2">
            <label>Port</label>
            <input type="text" name="Port" value="@entity.Port" class="form-control" />
        </div>
        <div class="col-12 col-sm-2">
            <label>Şema (Schema)</label>
            <input type="text" name="Sema" value="@entity.Sema" class="form-control" />
        </div>
        <div class="col-12 col-sm-12">
            <br />
            <p>Bilgilendirme : Sadece MS-SQL alt yapısı bulunan sunuculara bağlantı sağlamaktadır.</p>
        </div>
    </div>
    <div class="row">
        <div class="col-3 col-sm-2">
            <br />
            <input type="submit" name="name" value="Kaydet" class="btn btn-primary" />
        </div>
    </div>


</form>

IDReporting/Views/ID/Baglantilar.cshtml
@model List<IDReporting.Models.Baglantilar>
@{
    ViewBag.Title = "Veritabanı Bağlantı Listesi";
}

<h4>Veritabanı Bağlantı Listesi</h4>
<a href="@Url.Action("Baglanti","ID",new { id = 0 })">Yeni Bağlantı Ekle</a>
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Şube</th>
            <th>İsim</th>
            <th>Veritabanı</th>
            <th>Kullanıcı Adı</th>
            <th>Parola</th>
            <th>Port</th>
            <th>İşlem</th>
        </tr>
    </thead>
    <tbody>
        @foreach (IDReporting.Models.Baglantilar kullanici in Model)
        {
        <tr>
            <td>@kullanici.ID</td>
            <td>@kullanici.SubeID</td>
            <td>@kullanici.Isim</td>
            <td>@kullanici.Veritabani</td>
            <td>@kullanici.KullaniciAdi</td>
            <td>@kullanici.Parola</td>
            <td>@kullanici.Port</td>
            <td><a href="@Url.Action("Baglanti","ID",new { id = kullanici.ID })">Duzenle</a> | <a href="@Url.Action("BaglantiSil","ID",new { id = kullanici.ID })" onclick="return confirm('Silmek istediğinizden emin misini?')">Sil</a></td>
        </tr>
        }
    </tbody>
</table>

IDReporting/Views/ID/GenelParametreler.cshtml
@model List<IDReporting.Models.Parametreler>
@{
    ViewBag.Title = "Genel Parametreler";
}

<h4>Genel Parametreler</h4>
<form action="@Url.Action("GenelParametreler","ID",null)" method="post">
    <div class="row">

        <div class="col-12 col-sm-2">
            <label>E-Mail</label>
            <input type="text" name="Parametre_MailEmail" value="@(Model.Where((e)=>e.Tip == "Parametre_MailEmail").Count() > 0 ? Model.Where((e)=>e.Tip == "Parametre_MailEmail").First().Deger : "")" class="form-control" />
        </div>
        <div class="col-12 col-sm-2">
            <label>Parola</label>
            <input type="text" name="Parametre_MailParola" value="@(Model.Where((e)=>e.Tip == "Parametre_MailParola").Count() > 0 ? Model.Where((e)=>e.Tip == "Parametre_MailParola").First().Deger : "")" class="form-control" />
        </div>
        <div class="col-12 col-sm-2">
            <label>Server</label>
            <input type="text" name="Parametre_MailServer" value="@(Model.Where((e)=>e.Tip == "Parametre_MailServer").Count() > 0 ? Model.Where((e)=>e.Tip == "Parametre_MailServer").First().Deger : "")" class="form-control" />
        </div>
        <div class="col-12 col-sm-2">
            <label>Port</label>
            <input type="text" name="Parametre_MailPort" value="@(Model.Where((e)=>e.Tip == "Parametre_MailPort").Count() > 0 ? Model.Where((e)=>e.Tip == "Parametre_MailPort").First().Deger : "")" class="form-control" />
        </div>
        <div class="col-12 col-sm-2">
            <br />
            <label class="form-check-label">SSL</label>
            <input type="checkbox" name="Parametre_MailSSL" value="E" class="form-check-input" @((Model.Where((e) => e.Tip == "Parametre_MailSSL").Count() > 0 ? Model.Where((e) => e.Tip == "Parametre_MailSSL").First().Deger : "") == "E" ? "checked=\"true\"" : "") />
        </div>

    </div>
    <div class="row">
        <div class="col-12 col-sm-12">
            <label>Lisans Numarası</label>
            <input type="text" readonly name="Parametre_LisansNumarası" value="@(Model.Where((e)=>e.Tip == "Parametre_LisansNumarası").Count() > 0 ? Model.Where((e)=>e.Tip == "Parametre_LisansNumarası").First().Deger : "")" class="form-control" />
        </div>
    </div>
    <div class="row">
        <div class="col-3 col-sm-2">
            <br />
            <span>@ViewBag.Mesaj</span>
            <br />
            <input type="submit" name="name" value="Kaydet" class="btn btn-primary" />
        </div>
    </div>

</form>
@section Scripts {
    <script type="text/javascript">

    </script>
}

IDReporting/Views/ID/Kategoriler.cshtml
@model List<IDReporting.Models.Sorgular>
@using IDReporting.Models;
@{
    ViewBag.Title = "Kategori Listesi";
    IDReportingEntities db = new IDReportingEntities();
    int KategoriID = Convert.ToInt32(Request.QueryString["KategoriID"]);
}

<h4>Kategori Listesi - @db.Parametrelers.Where((e)=>e.ID == KategoriID).First().Deger</h4>
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Rapor Adı</th>
            <th>Tip</th>
            <th>Kayıt Tarihi</th>
        </tr>
    </thead>
    <tbody>
        @foreach (IDReporting.Models.Sorgular entity in Model)
        {
        <tr>
            <td>@entity.ID</td>
            <td><a href="@Url.Action("Sorgu","Rapor",new { id = entity.ID, Isim= entity.Isim })" target="_blank">@entity.Isim</a></td>
            <td>@entity.SorguTipi</td>
            <td>@entity.KayitTarihi</td>
        </tr>
        }
    </tbody>
</table>